# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f6c455cc85b68d3da6e4c5cad3dc965150d64bcc9ec90ed8428360250a0968c0f12f2b83c781c0903ee3f516636039018f3cf9eaa0a7dfba68c440b110c8cf

test:
  secret_key_base: 8c2a5c37acb5d9e3ecccfe899782caa1a58ba77cf5ed7f619a0a84447d991afc8a8713b1d9672d73a9cdaa74fb966b20e35e21a015bb6f7491938835d8edfca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
